# Generated by Django 4.1.2 on 2022-10-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('F', 'Full-time'), ('C', 'Contract'), ('R', 'Remote'), ('P', 'Part-time')], default='F', max_length=1)),
                ('experience_level', models.CharField(choices=[('E', 'Entry level'), ('M', 'Mid level'), ('S', 'Senior level')], default='E', max_length=1)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=200)),
            ],
        ),
    ]
