# Generated by Django 4.1.2 on 2022-10-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_jobapplication_job_advert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='github_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_advert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_app.jobadvert'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='linkedin_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='website',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
    ]
