# Generated by Django 4.1.2 on 2022-12-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0010_alter_jobadvert_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvert',
            name='employment_type',
            field=models.CharField(choices=[('Full', 'Full-time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Part', 'Part-time')], default='Full-time', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='experience_level',
            field=models.CharField(choices=[('Entry', 'Entry level'), ('Mid', 'Mid level'), ('Senior', 'Senior level')], default='Entry', max_length=20),
        ),
    ]
